import numpy as np
def first_part():
    my_list = [1,2,3]
    print(type(my_list))
    my_array = np.array(my_list)
    print(my_array)
    print(type(my_array))
    my_mx = [[1,2,3], [4,5,6], [7,8,9]]
    print(my_mx)
    my_matrix = np.array(my_mx)
    print(my_matrix)
    print(np.arange(6))
    print(np.arange(0,10))
    print(np.arange(3, 14, 2))
    print(np.arange(17, 2, -3))
    print(np.zeros(5))
    print(np.zeros((4,3)))
    print(np.ones((4,2)))
    print(np.linspace(0, 10, 3))
    print(np.linspace(0,10,4))
    print(np.linspace(0,10,5))
    print(np.eye(4))
def second_part():
    print(np.random.rand(1))
    print(np.random.rand(7))
    print(np.random.rand(4,3))
    print(np.random.randn(6))
    print(np.random.randn(2,3))
    print(np.random.randint(0,10,4))
    np.random.seed(42)
    print(np.random.rand(4))
    arr = np.arange(0,25)
    print(arr)
    print(arr.reshape(5,5))
    print("-----------------")
    random_array = np.random.randint(0,101,10)
    print(random_array)
    print(random_array.max())
    print(random_array.min())
    print(random_array.argmax())
    print(random_array.argmin())
    print(random_array.dtype)
    print(random_array.shape)
    random_array = random_array.reshape(5,2)
    print(random_array.shape)
    print("-----------------")
    r = np.random.randint(0,10, 15)
    print(r)
    print(r.shape)
    r = r.reshape(15,1)
    print(r)
    print(r.shape)
    r = r.reshape(1,15)
    print(r)
    print(r.shape)
def third_part():
    arr = np.arange(0, 11)
    print(arr)
    print(arr[2])
    print(arr[1:4])
    print(arr[2:9:2])
    print(arr[:5])
    print(arr[6:])
    print(arr)
    arr2 = arr.copy()
    arr[2:7] = 100
    print(arr)
    print(arr2)
    arr2[::3] = 100
    print(arr2)
    arr = np.arange(0,11)
    slice_of_array = arr[0:5]
    print(slice_of_array)
    slice_of_array[:] = 33
    print(slice_of_array)
    print(arr)
    slice_of_array[:] = 66
    print(arr)
    arr_copy = arr.copy()
    arr_copy[:] = 100
    print(arr_copy)
    print(arr)
    arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
    print(arr_2d[0])
    print(arr_2d[0][2])
    print(arr_2d[1][1])
    print(arr_2d[1,1])
    print(arr_2d)
    print(arr_2d[:2, 1:])
    arr = np.arange(0,10)
    print(arr % 2 == 0)
    print(arr[arr % 2 == 0])

arr = np.arange(0,10)
print(arr)
arr += 2
print(arr)
arr = np.arange(0, 10)
arr2 = np.arange(10,20)
print(arr)
print(arr2)
print(arr + arr2)
print(arr * 3)
##print(arr / arr)
##print(1 / arr)
print(np.sqrt(arr))
print(np.sin(arr))
print(arr.sum())
print(arr.var())
print(arr.std())
matrix = np.arange(25).reshape(5,5)
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))